name: sms_fraud_detector
version: 1.0.0+1
description: AI-based SMS Fraud Detection App using TFLite
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  tflite_flutter: ^0.10.3
  tflite_flutter_helper: ^0.3.0
  telephony: ^0.2.0
  provider: ^6.0.0
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true
  assets:
    - assets/fraud_detector.tflite
    - assets/tfidf_vocab.json 